# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: disqus_7B6WWisPyb
google_analytics: dbyll
title: Jignesh Patel

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Jignesh Patel's Blog

description: Learn to love maintaince 
author:
  name: Jignesh Patel
  email: jpatel@live.ca
  github: jpatel07
  twitter: tweet2jpatel
  #pinterest: asd123
  linkedin: jignesh-patel-05a45531
  bio: Software Developer
  email_md5: 08cff795d167ff87cc6edbb71125ba6c

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
#sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1
BASE_PATH:

plugins:
  - jekyll-paginate
